spring:
  application:
    name: demo-test-remote-db
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      # Параметри SSL для JDBC драйвера всередині HikariCP
      data-source-properties:
        sslmode: require
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Додатковий рівень захисту, якщо метадані не зчитуються автоматично
        temp:
          use_jdbc_metadata_defaults: false
